[project]
name = "cryojax_eo"
authors = [
    {name = "David Silva Sanchez", email = "david.silva@yale.edu"},
    {name = "Erik Henning Thiede"},
    {name = "Pilar Cossio"},
    {name = "Roy Lederman"},
]

description = "Cryo-EM Ensemble Optimization using JAX and OpenMM for Molecular Dynamics simulations."
readme = "README.md"
requires-python = ">=3.11"
keywords = ["jax", "equinox", "cryo-EM", "electron-microscopy", "molecular-dynamics"]
license = {file="LICENSE"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU Lesser General Public License v2 (LGPLv2)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
urls = {repository = "https://github.com/flatironinstitute/cryojax-ensemble-optimization" }
dynamic = ["version"]

dependencies = [
    "numpy",
    "jax",
    "jaxlib",
    "jaxtyping",
    "jaxopt",
    "jax_dataloader",
    "equinox",
    "natsort",
    "pydantic",
    "mdtraj",
    "tqdm",
    "cryojax",
    "openmm",
    "dm-pix",
    "optax",
    "optimistix",
    "PyYAML"
]

[project.optional-dependencies]
dev = [
  "pre-commit",
  "ruff"
]
tests = [
  "pytest"
]


[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/cryojax_eo/cryojax_eo_version.py"

[tool.ruff]
extend-include = ["*.ipynb"]
line-length = 90
src = ["src"]

[tool.ruff.lint]
fixable = ["I001", "F401", "UP"]
ignore = ["E402", "E721", "E731", "E741", "F722"]
select = ["E", "F", "I001", "UP"]

[tool.ruff.lint.isort]
combine-as-imports = true
extra-standard-library = ["typing_extensions"]
lines-after-imports = 2
order-by-type = true

[tool.black]
line-length = 90

[tool.pyright]
reportIncompatibleMethodOverride = true
reportIncompatibleVariableOverride = false  # Incompatible with eqx.AbstractVar
include = ["cryojax_eo", "tests"]

[project.scripts]
run_ensemble_optimization = "cryojax_eo.commands.run_ensemble_optimization:main_cli"
simulate_data = "cryojax_eo.commands.simulate_data:main_cli"
fit_gmm_to_atoms = "cryojax_eo.commands.fit_gmm_to_atoms:main_cli"
