name: Build and push container

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.6

      - name: Login to Sylabs
        run: |
          echo "${{ secrets.SYLABS_TOKEN }}" > /tmp/sylabs_token
          apptainer remote add --no-login SylabsCloud https://cloud.sylabs.io
          apptainer remote login --tokenfile /tmp/sylabs_token SylabsCloud
          rm /tmp/sylabs_token

      - name: Build container
        run: sudo apptainer build container/cryojax_eo.sif container/cryojax_eo.def

      - name: Push to Sylabs (latest and version tag)
        run: |
          apptainer push -U container/cryojax_eo.sif library://davidsilva27/default/cryojax_eo:latest
          apptainer push -U container/cryojax_eo.sif library://davidsilva27/default/cryojax_eo:${{ github.ref_name }}
